name: "status_update"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "*/5 * * * *"
jobs:
  status_update:
    name: "status_update"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Check
      run: |
        python3 status_update.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update status